name: ladderenv  # Ganti dengan nama environment yang diinginkan
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cudatoolkit=11.8.0
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.1.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.27
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.3.0
  - python=3.10.12
  - readline=8.2
  - sqlite=3.42.0
  - tk=8.6.12
  - xz=5.2.6
  - zlib=1.2.13
  - pip
  - setuptools
  - wheel
  - pip:
      - absl-py==2.1.0
      - accelerate==0.27.2
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - altair==5.0.1
      - anyio==3.7.1
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - cachetools==5.3.3
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.2
      - colorama==0.4.6
      - contourpy==1.1.0
      - datasets==2.14.4
      - deepspeed==0.13.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - entmax==1.3
      - evaluate==0.4.1
      - fastapi==0.95.1
      - ffmpy==0.3.1
      - filelock==3.12.2
      - fire==0.6.0
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==3.40.1
      - gradio-client==0.4.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.21.1
      - idna==3.4
      - ijson==3.2.3
      - ipadic==1.0.0
      - jieba==0.42.1
      - joblib==1.3.2
      - jsonargparse==3.13.1
      - jsonschema==4.19.0
      - matplotlib==3.7.2
      - mecab-python3==1.0.6
      - nltk==3.8.1
      - numpy==1.25.2
      - orjson==3.9.5
      - pandas==2.0.3
      - peft==0.10.0
      - pyarrow==12.0.1
      - pydantic==1.10.11
      - python-multipart==0.0.6
      - pytorch-lightning==2.2.1
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - transformers==4.38.2
      - uvicorn==0.23.2
      - wandb==0.16.6
